### ISSUE TITLE
npm start  WRONG!

### ISSUE THREAD

**Issue by Tzxhy** [babel/babel.github.io#1196]
I installed Jekyll and all of it needs, I can build a local server and it  works very well.  After I ran  __npm install__ and __npm start__ , it fails. 
here's wrong message. 
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart babel.github.io@1.0.0
6 info start babel.github.io@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info babel.github.io@1.0.0 Failed to exec start script
9 verbose stack Error: babel.github.io@1.0.0 start: `make serve`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid babel.github.io@1.0.0
11 verbose cwd C:\Users\Tzx\Desktop\react-helo\babel.github.io
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error babel.github.io@1.0.0 start: `make serve`
17 error Exit status 1
18 error Failed at the babel.github.io@1.0.0 start script 'make serve'.
18 error This is most likely a problem with the babel.github.io package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     make serve
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs babel.github.io
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls babel.github.io
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

what's the __make__  command? Can anybody help me?  Thanks.

**Comment by xtuc** [comment]
[make](https://linux.die.net/man/1/make) is an Linux command. Have you tried with tools like Cygwin? The Ubuntu console?

**Comment by Tzxhy** [comment]
@xtuc  I used Jekyll finally  (although I dont know much about it), and it worked well. at the meantime, thank you for mentioning Cygwin, which is good for me to learn.
