### ISSUE TITLE
ReferenceError: Unknown transformer es6.parameters specified in whitelist

### ISSUE THREAD

**Issue by shangsunset** [babel/babel.github.io#533]
```
/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/transformation/pipeline.js:162
        throw new ReferenceError("Unknown transformer " + key + " specified in " + type);
        ^

ReferenceError: Unknown transformer es6.parameters specified in whitelist
    at Pipeline._ensureTransformerNames (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/transformation/pipeline.js:162:15)
    at Function.transformerList.validate (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/transformation/file/options/parsers.js:25:19)
    at validateOption (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/transformation/file/options/index.js:25:19)
    at File.normaliseOptions (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/transformation/file/index.js:192:50)
    at new File (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/transformation/file/index.js:146:10)
    at Pipeline.transform (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/transformation/pipeline.js:121:16)
    at Object.transformFileSync (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/api/node.js:112:42)
    at compile (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/api/register/node.js:109:20)
    at normalLoader (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/api/register/node.js:160:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shangyeshen/Sites/react-native-fbsdk/Sample/node_modules/react-native/node_modules/babel-core/lib/babel/api/register/node.js:173:7)
```

get this error when trying to run some example code on facebook/react-native-fbsdk. not sure whats causing this. i have a .babelrc file in my $HOME dir.

**Comment by thejameskyle** [comment]
Wrong repo for Babel issues. Also this is a support question so you please see our [README](https://github.com/babel/babel/blob/master/README.md):

> For questions and support please visit the <a href="https://babel-slack.herokuapp.com">Slack community</a> or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

I'd be happy to help with any other question you have there.
