### ISSUE TITLE
unknown node of type "NumberLiteral" with constructor "Node"

### ISSUE THREAD

**Issue by AntouanK** [babel/babel.github.io#585]
I'm using browserify and babelify in my project.
The way things changed now, I use presets "es2015" and "react".
Today, I updated to the latest versions ( see at the bottom ).

I get now an error that says 
```
ReferenceError: /Users/.../showcase/configuration.js: unknown node of type "NumberLiteral" with constructor "Node"
    at CodeGenerator.print (/Users/.../showcase/node_modules/babel-generator/lib/printer.js:67:13)
    at CodeGenerator.ObjectProperty (/Users/.../showcase/node_modules/babel-generator/lib/generators/types.js:86:8)
    at CodeGenerator._print (/Users/.../showcase/node_modules/babel-generator/lib/printer.js:141:19)
    at CodeGenerator.print (/Users/.../showcase/node_modules/babel-generator/lib/printer.js:86:10)
    at CodeGenerator.printJoin (/Users/.../showcase/node_modules/babel-generator/lib/printer.js:176:12)
    at CodeGenerator.printList (/Users/.../showcase/node_modules/babel-generator/lib/printer.js:241:17)
    at CodeGenerator.ObjectExpression (/Users/.../showcase/node_modules/babel-generator/lib/generators/types.js:48:10)
    at CodeGenerator._print (/Users/.../showcase/node_modules/babel-generator/lib/printer.js:141:19)
    at CodeGenerator.print (/Users/.../showcase/node_modules/babel-generator/lib/printer.js:86:10)
    at CodeGenerator.AssignmentExpression (/Users/.../showcase/node_modules/babel-generator/lib/generators/expressions.js:212:8)
```

And I see that it's caused by a piece of code that looks like this:
```
module.exports = {
  port: 3001
}
```
If I change that value to a string, it's fine. So why having a number there causes an error??

Thanks.

( it's overwhelming to keep up with all of those packages, see list below )
```
➜  showcase git:(feature/tabs) ✗ npm ls | grep babel
├── babel@6.1.18
├─┬ babel-preset-es2015@6.1.18
│ ├─┬ babel-plugin-check-es2015-constants@6.2.0
│ │ └── babel-runtime@5.8.34
│ ├── babel-plugin-transform-es2015-arrow-functions@6.1.18
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.1.18
│ ├─┬ babel-plugin-transform-es2015-block-scoping@6.1.18
│ │ ├── babel-template@6.2.0
│ │ ├─┬ babel-traverse@6.2.0
│ │ ├─┬ babel-types@6.2.0
│ ├─┬ babel-plugin-transform-es2015-classes@6.2.0
│ │ ├── babel-helper-define-map@6.2.0
│ │ ├── babel-helper-function-name@6.2.0
│ │ ├── babel-helper-optimise-call-expression@6.1.18
│ │ ├── babel-helper-replace-supers@6.2.0
│ │ └── babel-messages@6.2.0
│ ├── babel-plugin-transform-es2015-computed-properties@6.1.18
│ ├── babel-plugin-transform-es2015-destructuring@6.1.18
│ ├── babel-plugin-transform-es2015-for-of@6.1.18
│ ├── babel-plugin-transform-es2015-function-name@6.1.18
│ ├── babel-plugin-transform-es2015-literals@6.1.18
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.2.0
│ │ └── babel-plugin-transform-strict-mode@6.2.0
│ ├── babel-plugin-transform-es2015-object-super@6.1.18
│ ├─┬ babel-plugin-transform-es2015-parameters@6.1.18
│ │ ├─┬ babel-helper-call-delegate@6.2.0
│ │ │ └── babel-helper-hoist-variables@6.1.18
│ │ └── babel-helper-get-function-arity@6.2.0
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.1.18
│ ├── babel-plugin-transform-es2015-spread@6.1.18
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.1.18
│ │ └── babel-helper-regex@6.1.18
│ ├── babel-plugin-transform-es2015-template-literals@6.1.18
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.1.18
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.1.18
│ └─┬ babel-plugin-transform-regenerator@6.2.0
│   ├─┬ babel-core@6.2.0
│   │ ├── babel-register@6.2.0
│   ├── babel-plugin-syntax-async-functions@6.1.18
├─┬ babel-preset-react@6.1.18
│ ├── babel-plugin-syntax-flow@6.1.18
│ ├── babel-plugin-syntax-jsx@6.1.18
│ ├── babel-plugin-transform-flow-strip-types@6.1.18
│ ├── babel-plugin-transform-react-display-name@6.1.18
│ ├─┬ babel-plugin-transform-react-jsx@6.2.0
│ │ └── babel-helper-builder-react-jsx@6.2.0
│ └── babel-plugin-transform-react-jsx-source@6.1.18
├─┬ babelify@7.2.0
│ ├─┬ babel-core@6.0.16
│ │ ├─┬ babel-code-frame@6.1.18
│ │ ├─┬ babel-generator@6.2.0
│ │ ├── babel-helpers@6.1.20
```

**Comment by aamirafridi** [comment]
Thats unrelated to this repo.

**Comment by hzoo** [comment]
Yes like @aamirafridi said this is the website repo - report on phabricator.babeljs.io
