### ISSUE TITLE
strange TypeError 

### ISSUE THREAD

**Issue by zbyte64** [babel/babel.github.io#589]
Recently upgraded to Babel 6.1.18 on a code base that was using Babel 5. Running babel-node on that code base gives me the following stack trace:

```
jason@jason-Lemur-Ultra:~/Repos/project-webinator/maker$ babel-node --presets es2015 --presets stage-1 -- server/app.js 
/home/jason/Repos/project-webinator/maker/node_modules/babel-runtime/helpers/typeof.js:14
mbol" : typeof obj === "undefined" ? "undefined" : (0, _typeof3.default)(obj);
                                                                        ^
TypeError: object is not a function
    at exports.default (/home/jason/Repos/project-webinator/maker/node_modules/babel-runtime/helpers/typeof.js:14:174)
    at Object.<anonymous> (/home/jason/Repos/project-webinator/maker/node_modules/babel-runtime/regenerator/runtime.js:661:69)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jason/.nvm/versions/node/v0.12.7/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:135:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/jason/Repos/project-webinator/maker/node_modules/babel-runtime/regenerator/index.js:19:18)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jason/.nvm/versions/node/v0.12.7/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:135:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

I nuked all previous babel installs but this is still happening.

**Comment by zbyte64** [comment]
Running `babel --presets es2015 server --out-dir sdist` works though.

**Comment by thejameskyle** [comment]
Not the appropriate place for this
