### ISSUE TITLE
BABEL_DISABLE_CACHE=1 can't work

### ISSUE THREAD

**Issue by hujb2000** [babel/babel.github.io#608]
Allthings is normal When I first run  my program ,but The second run it and will throw  that I have no anything  change to soucecode and configuration .
 
throw err msg:
    ReferenceError: _callee3 is not defined
    at _callee3 (main.js:222:20)
    at /Users/hujiabao/workspace_docker/3easynode/node_modules/co/index.js:50:46
    at new Promise (/usr/local/lib/node_modules/babel-cli/node_modules/core-js/modules/es6.promise.js:197:7)
    at co (/Users/hujiabao/workspace_docker/3easynode/node_modules/co/index.js:49:10)
    at main (main.js:25:9)
    at Object.<anonymous> (main.js:224:2)
    at Module._compile (module.js:430:26)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:127:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:137:7)
    at Module.load (module.js:355:32)
 
I think of  closing babel cache can solve this problem,  so I run like this 
BABEL_DISABLE_CACHE=1 BABEL_CACHE_PATH=my-cache.json sh start.sh
but the problem still exist,  That's Why ? 
 
I would appriciate an early reply!

**Comment by thejameskyle** [comment]
Not the correct place for issues in Babel. See: https://phabricator.babeljs.io
