### ISSUE TITLE
Some change from today broke our CI

### ISSUE THREAD

**Issue by KenanSulayman** [babel/babel.github.io#682]
Hi,

we're started having issues when an update was issued today (6.4.3) of a transform plugin used in babel.

The babel presets used in the respective service are `es2015` and `stage-3`.

The changes introduced broke this code in our repository:

### 1

```
export const fields = {
	// ...

	/* jshint ignore:start */
	async resolve (root, { query, lang }) {
		const items = await search.query({
			query
		});

		return items.map(item => {
			item.args = {query, lang};

			return item;
		});
	}
	/* jshint ignore:end */

	// ...
};
```

It throws this error now:

```
<redacted>/node_modules/babel-core/lib/transformation/file/index.js:548
      throw err;
      ^

SyntaxError: <redacted>/server/schemas/offerType.js: "items" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)

<file redacted>

    at File.buildCodeFrameError (<redacted>/node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at NodePath.buildCodeFrameError (<redacted>/node_modules/babel-traverse/lib/path/index.js:148:26)
    at PluginPass.Scope (<redacted>/node_modules/babel-plugin-check-es2015-constants/lib/index.js:33:29)
    at PluginPass.newFn (<redacted>/node_modules/babel-traverse/lib/visitors.js:309:17)
    at newFn (<redacted>/node_modules/babel-traverse/lib/visitors.js:276:19)
    at NodePath._call (<redacted>/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (<redacted>/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (<redacted>/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (<redacted>/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (<redacted>/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (<redacted>/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (<redacted>/node_modules/babel-traverse/lib/index.js:139:17)
```

Fixed by making `items` non-constant (`let items`).

### 2

```
export var redacted = Promise.coroutine(function* (foo) {
	const item = bar.get(foo);

	// ...

	return item;
});
```

It throws this error now:

```
<redacted>/node_modules/babel-core/lib/transformation/file/index.js:548
      throw err;

SyntaxError: <redacted>/some/file.js: "item" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)

<file redacted>

    at File.buildCodeFrameError (<redacted>/node_modules/babel-core/lib/transformation/file/index.js:408:15)
    at NodePath.buildCodeFrameError (<redacted>/node_modules/babel-traverse/lib/path/index.js:148:26)
    at PluginPass.Scope (<redacted>/node_modules/babel-plugin-check-es2015-constants/lib/index.js:33:29)
    at PluginPass.newFn (<redacted>/node_modules/babel-traverse/lib/visitors.js:309:17)
    at newFn (<redacted>/node_modules/babel-traverse/lib/visitors.js:276:19)
    at NodePath._call (<redacted>/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (<redacted>/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (<redacted>/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (<redacted>/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitMultiple (<redacted>/node_modules/babel-traverse/lib/context.js:108:17)
    at TraversalContext.visit (<redacted>/node_modules/babel-traverse/lib/context.js:195:19)
    at Function.traverse.node (<redacted>/node_modules/babel-traverse/lib/index.js:139:17)
```

---

Since both of the instances that broke are being compiled to regeneratorRuntime (`async/await` and `generator`), I assume it was a change to a "generator" transformer?

For now we changed the respective places to `let <variable>` so that our CI deploys again.

Thanks in advance

**Comment by KenanSulayman** [comment]
I see this is already an ongoing issue, closing.
