### ISSUE TITLE
TypeError: src/index.js: Property name of JSXOpeningElement expected node to be of a type ["JSXIdentifier","JSXMemberExpression"] but instead got "MemberExpression"

### ISSUE THREAD

**Issue by volkanunsal** [babel/babel.github.io#870]
I'm getting this error from the following code:

``` js
return enabledDecks.map(({adapter, config, options, on}) => <Plate
      config={config}
      options={options}
      map={this.map}
      adapter={adapter}
      key={config.name}
      on={on}
    />);
```

The `Plate` class looks like this:

``` js
export default class Plate extends Component {
...
}
```

This is the rest of the backtrace output:

```
at Object.validate (/Users/newuser/w/folio/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/newuser/w/folio/node_modules/babel-types/lib/index.js:541:9)
    at NodePath._replaceWith (/Users/newuser/w/folio/node_modules/babel-traverse/lib/path/replacement.js:208:7)
    at NodePath.replaceWith (/Users/newuser/w/folio/node_modules/babel-traverse/lib/path/replacement.js:186:8)
    at Object.ReferencedIdentifier (/Users/newuser/w/folio/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:36:14)
    at Object.newFn (/Users/newuser/w/folio/node_modules/babel-traverse/lib/visitors.js:334:17)
    at NodePath._call (/Users/newuser/w/folio/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/newuser/w/folio/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/newuser/w/folio/node_modules/babel-traverse/lib/path/context.js:106:12)
    at TraversalContext.visitQueue (/Users/newuser/w/folio/node_modules/babel-traverse/lib/context.js:167:16)
```

Can you advise me on what I should be doing here? Thanks.

**Comment by hzoo** [comment]
If you can provide your config and minimal reproduction steps we can help with this - (this is the website repo, so please report on https://github.com/babel/babel/issues)
